export const projects = [
  {
    name: "LoveMe App",
    link: "https://love-me.app",
    git: "https://github.com/workshopapps/loveletterwriter.web",
    image: "/project2.jpg",
    description: "Generate, edit and send love letters to your loved ones",
  },
  {
    name: "Quizzical",
    link: "https://juicio-quizzical.netlify.app",
    git: "https://github.com/juicio8/Quizzical",
    image: "/project1.jpg",
    description: "Answer top quizzes and get score",
  },
  {
    name: "WatchList",
    link: "https://sweet-gecko-45be45.netlify.app",
    git: "https://github.com/juicio8/Movie-WatchList",
    image: "/project3.jpg",
    description: "Select your favorite films and add it to your WatchList",
  },
  {
    name: "Lendsqr Test",
    link: "https://deni-wisdom-ochiche-lendsqr-fe-test.netlify.app",
    git: "https://github.com/juicio8/lendsqr-fe-test",
    image: "/project4.jpg",
    description: "",
  },
  {
    name: "Metabnb",
    link: "https://lambent-khapse-f0075f.netlify.app",
    git: "https://github.com/juicio8/Metabnb",
    image: "/project5.jpg",
    description: "",
  },
  {
    name: "Travel Journal",
    link: "https://magnificent-lokum-ace742.netlify.app",
    git: "",
    image: "/project6.jpg",
    description: "",
  },
  {
    name: "Metric Conversion",
    link: "https://reliable-speculoos-d172f8.netlify.app",
    git: "https://github.com/juicio8/Metric-converter",
    image: "/project7.jpg",
    description: "",
  },
  {
    name: "Random Password",
    link: "https://vermillion-malabi-b39f5d.netlify.app",
    git: "https://github.com/juicio8/Password-Generator",
    image: "/project8.jpg",
    description: "",
  },
  {
    name: "Scoreboard",
    link: "https://creative-belekoy-cd83ca.netlify.app",
    git: "https://github.com/juicio8/scoreboard",
    image: "/project9.jpg",
    description: "",
  },
  {
    name: "Portfolio",
    link: "https://creative-belekoy-cd83ca.netlify.app",
    git: "https://github.com/juicio8/Portfolio",
    image: "/project10.jpg",
    description: "",
  },
];
